#pragma once

#include <stdexcept>
#include <string>
#include <type_traits>
#include <utility>

#include <batchlas/backend_config.h>
#include <batchlas/blas/enums.hh>
#include <batchlas/settings.hh>
#include <batchlas/blas/matrix.hh>
#include <batchlas/util/sycl-device-queue.hh>

/// @file
/// @brief Backend deduction from the Queue, owning-argument acceptance and the USM pointer check.
/// @ingroup dispatch

namespace batchlas {

/**
 * @addtogroup dispatch
 * @details
 * <b>Every entry point has two spellings.</b> `f<Backend::CUDA>(ctx, ...)` fixes the
 * backend at compile time; `f(ctx, ...)` takes it from `ctx.backend()` through
 * with_backend(). The deducing overload of a positional entry point is generated by
 * `BATCHLAS_DISPATCH_ON_QUEUE(f)`, and the option-struct overloads in
 * `blas/options.hh` deduce the same way. Library code templated on `Backend` must
 * call the `f<B>` spelling, never the deducing one.
 *
 * <b>Every entry point also accepts owning arguments.</b> Wherever a positional
 * primary takes a `MatrixView` or `VectorView`, an owning `Matrix` or `Vector` may be
 * passed instead (the option-struct overloads take `Matrix` or `MatrixView` directly),
 * in any position and mixed freely with views; `T` and `MatrixFormat` are deduced
 * from it as they would be from its view. `BATCHLAS_ACCEPT_OWNING(f)` (and
 * `BATCHLAS_ACCEPT_OWNING_NB(f)` for entry points not templated on `Backend`)
 * generates these overloads. Two argument lists are not accepted: a bare `{}` in
 * any position (name the type, e.g. `PotrfOptions{}`), and a call that names some
 * template arguments and leaves others to deduction (`spmm<Back, T>(ctx, Matrix, ...)`;
 * write `spmm<Back>(ctx, ...)`). Both are compile errors, never wrong answers.
 *
 * <b>Pointer checks.</b> The deducing spellings check that every non-empty pointer
 * argument is reachable from the queue's device and throw `std::invalid_argument`
 * naming the argument otherwise; the `f<Backend>` spellings do not check.
 * `BATCHLAS_SKIP_POINTER_CHECKS` turns the check off (latched once per process).
 *
 * The generating macros are omitted from this reference; see @ref design_api_conventions
 * for their design and traps.
 * @{
 */

/// @brief Call @p f with the queue's backend as a compile-time constant.
///
/// Converts `ctx.backend()` into `std::integral_constant<Backend, B>` and invokes
/// `f` with it, so the body can name `B.value` as a template argument:
/// @code
/// with_backend(ctx, [&](auto B) { return gemm<B.value, T>(ctx, ...); });
/// @endcode
/// This is a `switch` over existing instantiations, not a virtual call.
/// @tparam F     callable taking `std::integral_constant<Backend, B>`
/// @param ctx    queue whose backend is dispatched on
/// @param f      callable; every branch must return the same type
/// @return       whatever @p f returns
/// @throws batchlas::unsupported if `ctx.backend()` has no implementation in this
///         build (always the case for Backend::MAGMA and Backend::SYCL)
/// @see Queue::backend_available
template <typename F>
inline auto with_backend(Queue& ctx, F&& f) {
    static_assert(BATCHLAS_HAS_CUDA_BACKEND || BATCHLAS_HAS_ROCM_BACKEND ||
                      BATCHLAS_HAS_MKL_BACKEND || BATCHLAS_HAS_HOST_BACKEND,
                  "BatchLAS was built with no backends; nothing can be dispatched.");

    switch (ctx.backend()) {
#if BATCHLAS_HAS_CUDA_BACKEND
        case Backend::CUDA:
            return f(std::integral_constant<Backend, Backend::CUDA>{});
#endif
#if BATCHLAS_HAS_ROCM_BACKEND
        case Backend::ROCM:
            return f(std::integral_constant<Backend, Backend::ROCM>{});
#endif
#if BATCHLAS_HAS_MKL_BACKEND
        case Backend::MKL:
            return f(std::integral_constant<Backend, Backend::MKL>{});
#endif
#if BATCHLAS_HAS_HOST_BACKEND
        case Backend::NETLIB:
            return f(std::integral_constant<Backend, Backend::NETLIB>{});
#endif
        default:
            break;
    }
    throw batchlas::unsupported(
        std::string("BatchLAS: backend ") + std::string(to_string(ctx.backend())) +
        " has no implementation in this build. "
        "Check Queue::backend_available() before pinning a backend.");
}

/// @}

namespace detail {

// USM contract, enforced: host memory on a GPU queue throws invalid_argument here
// instead of aborting in the runtime. Latched once (it is on every call's path), so
// a settings reload does not reach it. Any value of BATCHLAS_SKIP_POINTER_CHECKS not
// starting with '0' disables it ("=off" too); do not tighten that to env_truthy.
// evidence: docs/design/api-conventions.md#api-conventions-the-usm-pointer-check
inline bool pointer_checks_enabled() {
    static const bool enabled = !batchlas::settings().unsafe.skip_pointer_checks;
    return enabled;
}

// Matrix/MatrixView spell it data_ptr(); Span/UnifiedVector spell it data().
template <typename A>
concept HasDataPtr = requires(const A& a) { { a.data_ptr() } -> std::convertible_to<const void*>; };
template <typename A>
concept HasData = requires(const A& a) {
    { a.data() } -> std::convertible_to<const void*>;
    { a.size() } -> std::convertible_to<size_t>;
};

// Extents: MatrixView rows()/cols()/batch_size(); VectorView size()/batch_size().
template <typename A>
concept HasMatrixExtent = requires(const A& a) {
    { a.rows() } -> std::convertible_to<long long>;
    { a.cols() } -> std::convertible_to<long long>;
    { a.batch_size() } -> std::convertible_to<long long>;
};
template <typename A>
concept HasVectorExtent = requires(const A& a) {
    { a.size() } -> std::convertible_to<long long>;
    { a.batch_size() } -> std::convertible_to<long long>;
};

// True when no kernel can dereference the argument, whatever its pointer.
template <typename A>
inline bool addresses_no_elements(const A& arg) {
    using U = std::remove_cvref_t<A>;
    if constexpr (HasMatrixExtent<U>) {
        return arg.rows() == 0 || arg.cols() == 0 || arg.batch_size() == 0;
    } else if constexpr (HasVectorExtent<U>) {
        return arg.size() == 0 || arg.batch_size() == 0;
    } else {
        return false;
    }
}

template <typename A>
inline void require_arg_accessible(const Queue& ctx, const A& arg, const std::string& what) {
    if constexpr (HasDataPtr<std::remove_cvref_t<A>>) {
        // A default-constructed view means "optional matrix not in use"; it must pass.
        if (addresses_no_elements(arg)) return;
        ctx.require_device_accessible(static_cast<const void*>(arg.data_ptr()), what.c_str());
    } else if constexpr (HasData<std::remove_cvref_t<A>>) {
        // BumpAllocator sizing passes hand out empty spans by design.
        if (arg.size() != 0) {
            ctx.require_device_accessible(static_cast<const void*>(arg.data()), what.c_str());
        }
    }
    // Anything else (option structs, scalars, enums) carries no pointer.
}

// Positional labelling: the dispatch macro forwards an unnamed pack.
template <typename... Args>
inline void require_pack_accessible(const Queue& ctx, const char* fn, const Args&... args) {
    if (!pointer_checks_enabled()) return;
    int pos = 0;
    (void)std::initializer_list<int>{
        (++pos,
         require_arg_accessible(ctx, args,
                                std::string(fn) + ": argument " + std::to_string(pos)),
         0)...};
}

// Any compiled-in backend; used only to probe "is the positional call well-formed?".
inline constexpr Backend kProbeBackend =
#if BATCHLAS_HAS_CUDA_BACKEND
    Backend::CUDA;
#elif BATCHLAS_HAS_ROCM_BACKEND
    Backend::ROCM;
#elif BATCHLAS_HAS_MKL_BACKEND
    Backend::MKL;
#else
    Backend::NETLIB;
#endif

// Owning arguments: deduction ignores Matrix -> MatrixView conversions, so the view
// is named here. Non-owning arguments pass through as themselves.
// evidence: docs/design/api-conventions.md#api-conventions-owning-matrix-and-vector-arguments
template <class A>
struct view_of {
    using type = const A&;
};
template <class T, MatrixFormat F>
struct view_of<Matrix<T, F>> {
    using type = MatrixView<T, F>;
};
template <class T>
struct view_of<Vector<T>> {
    using type = VectorView<T>;
};
template <class A>
using view_t = typename view_of<std::remove_cvref_t<A>>::type;

// True for exactly the argument types view_of rewrites.
template <class A>
inline constexpr bool is_owning_arg_v =
    !std::is_same_v<view_t<A>, const std::remove_cvref_t<A>&>;

// Gate on the owning forwarder: without it the forwarder claims every call.
template <class... A>
concept AnyOwning = (is_owning_arg_v<A> || ...);

template <class A>
inline view_t<A> as_view(const A& a) {
    return static_cast<view_t<A>>(a);
}

}  // namespace detail

}  // namespace batchlas

// Backend-deducing overload `NAME(ctx, args...)` of `NAME<Backend, T, ...>(ctx, ...)`.
// The pack is forwarded, not restated, so the primary's defaults still apply. The
// requires-clause must stay: unconstrained, this beats option-struct overloads and
// fails inside its body. Even constrained, it beats `const MA&` for prvalues, so
// checks must also live on the <Backend> option overloads.
// evidence: docs/design/api-conventions.md#api-conventions-the-variadic-dispatch-overload-and-its-requires-clause
#define BATCHLAS_DISPATCH_ON_QUEUE(NAME)                                        \
    template <typename... Args>                                                 \
        requires requires(Queue& probe_ctx, Args&&... probe_args) {             \
            NAME<::batchlas::detail::kProbeBackend>(probe_ctx,                  \
                                                    std::forward<Args>(probe_args)...); \
        }                                                                       \
    inline auto NAME(Queue& ctx, Args&&... args) {                              \
        ::batchlas::detail::require_pack_accessible(ctx, #NAME, args...);       \
        return ::batchlas::with_backend(ctx, [&](auto Back) {                   \
            return NAME<Back.value>(ctx, std::forward<Args>(args)...);          \
        });                                                                     \
    }

// Owning-argument overload of every `NAME<Back>` spelling at once; the inner call
// deduces, so no signature is restated. Last resort by construction (AnyOwning plus
// the requires-clause). The pack is `const Args&...`, NEVER `Args&&...`: a
// forwarding pack beats the checked option overloads for prvalues (an 8x4 matrix
// once passed getrf's squareness check that way). A bare `{}` or a partly explicit
// template argument list does not reach it, by design.
// evidence: docs/design/api-conventions.md#api-conventions-the-owning-pack-is-const-args-never-args
#define BATCHLAS_ACCEPT_OWNING(NAME)                                            \
    template <Backend Back, typename... Args>                                   \
        requires ::batchlas::detail::AnyOwning<Args...> &&                      \
                 requires(Queue& probe_ctx, const Args&... probe_args) {        \
                     NAME<Back>(probe_ctx,                                      \
                                ::batchlas::detail::as_view(probe_args)...);    \
                 }                                                              \
    inline auto NAME(Queue& ctx, const Args&... args) {                         \
        return NAME<Back>(ctx, ::batchlas::detail::as_view(args)...);           \
    }

// BATCHLAS_ACCEPT_OWNING for an entry point not templated on Backend (norm,
// transpose, francis_sweep, steqr_*_buffer_size); those have no dispatch overload.
#define BATCHLAS_ACCEPT_OWNING_NB(NAME)                                         \
    template <typename... Args>                                                 \
        requires ::batchlas::detail::AnyOwning<Args...> &&                      \
                 requires(Queue& probe_ctx, const Args&... probe_args) {        \
                     NAME(probe_ctx,                                            \
                          ::batchlas::detail::as_view(probe_args)...);          \
                 }                                                              \
    inline auto NAME(Queue& ctx, const Args&... args) {                         \
        return NAME(ctx, ::batchlas::detail::as_view(args)...);                 \
    }
