#include "backend_handle_impl.hh"

#include "../util/template-instantiations.hh"

namespace batchlas {

#define BACKEND_MATRIX_HANDLE_INSTANTIATE(fp, fmt) \
template struct BackendMatrixHandle<BATCHLAS_UNPAREN fp, fmt>;

#define BACKEND_MATRIX_HANDLE_INSTANTIATE_DENSE(fp) \
	BACKEND_MATRIX_HANDLE_INSTANTIATE(fp, MatrixFormat::Dense)

#define BACKEND_MATRIX_HANDLE_INSTANTIATE_CSR(fp) \
	BACKEND_MATRIX_HANDLE_INSTANTIATE(fp, MatrixFormat::CSR)

BATCHLAS_FOR_EACH_SCALAR_TYPE(BACKEND_MATRIX_HANDLE_INSTANTIATE_DENSE)
BATCHLAS_FOR_EACH_SCALAR_TYPE(BACKEND_MATRIX_HANDLE_INSTANTIATE_CSR)

#define CREATE_BACKEND_HANDLE_INSTANTIATE(fp, fmt) \
template std::shared_ptr<BackendMatrixHandle<BATCHLAS_UNPAREN fp, fmt>> createBackendHandle<BATCHLAS_UNPAREN fp, fmt>(const Matrix<BATCHLAS_UNPAREN fp, fmt>& matrix);

#define CREATE_BACKEND_HANDLE_INSTANTIATE_DENSE(fp) \
	CREATE_BACKEND_HANDLE_INSTANTIATE(fp, MatrixFormat::Dense)

#define CREATE_BACKEND_HANDLE_INSTANTIATE_CSR(fp) \
	CREATE_BACKEND_HANDLE_INSTANTIATE(fp, MatrixFormat::CSR)

BATCHLAS_FOR_EACH_SCALAR_TYPE(CREATE_BACKEND_HANDLE_INSTANTIATE_DENSE)
BATCHLAS_FOR_EACH_SCALAR_TYPE(CREATE_BACKEND_HANDLE_INSTANTIATE_CSR)

#undef CREATE_BACKEND_HANDLE_INSTANTIATE_CSR
#undef CREATE_BACKEND_HANDLE_INSTANTIATE_DENSE
#undef CREATE_BACKEND_HANDLE_INSTANTIATE
#undef BACKEND_MATRIX_HANDLE_INSTANTIATE_CSR
#undef BACKEND_MATRIX_HANDLE_INSTANTIATE_DENSE
#undef BACKEND_MATRIX_HANDLE_INSTANTIATE

} // namespace batchlas
