#pragma once

// This file is auto-generated by evaluation/tuning/generate_tuning_header.py.
// Source profile: build/tuning/profile.json
// Do not edit manually.

#include <cstdint>

namespace batchlas::tuning {

inline constexpr int32_t ORMQR_BLOCK_SIZE_TINY = 16;
inline constexpr int32_t ORMQR_BLOCK_SIZE_SMALL = 16;
inline constexpr int32_t ORMQR_BLOCK_SIZE_MEDIUM = 16;
inline constexpr int32_t ORMQR_BLOCK_SIZE_LARGE = 16;
inline constexpr int32_t ORMQR_BLOCK_SIZE_XLARGE = 16;

inline constexpr int32_t SYTRD_BLOCK_SIZE_TINY = 8;
inline constexpr int32_t SYTRD_BLOCK_SIZE_SMALL = 16;
inline constexpr int32_t SYTRD_BLOCK_SIZE_MEDIUM = 16;
inline constexpr int32_t SYTRD_BLOCK_SIZE_LARGE = 16;
inline constexpr int32_t SYTRD_BLOCK_SIZE_XLARGE = 16;

inline constexpr int32_t LATRD_LOWER_PANEL_WG_HINT = 0;

inline constexpr int32_t STEDC_RECURSION_THRESHOLD_TINY = 32;
inline constexpr int32_t STEDC_RECURSION_THRESHOLD_SMALL = 32;
inline constexpr int32_t STEDC_RECURSION_THRESHOLD_MEDIUM = 32;
inline constexpr int32_t STEDC_RECURSION_THRESHOLD_LARGE = 32;
inline constexpr int32_t STEDC_RECURSION_THRESHOLD_XLARGE = 32;

inline constexpr int32_t STEDC_MERGE_VARIANT_TINY = 2;
inline constexpr int32_t STEDC_MERGE_VARIANT_SMALL = 2;
inline constexpr int32_t STEDC_MERGE_VARIANT_MEDIUM = 2;
inline constexpr int32_t STEDC_MERGE_VARIANT_LARGE = 2;
inline constexpr int32_t STEDC_MERGE_VARIANT_XLARGE = 2;

inline constexpr int32_t STEDC_THREADS_PER_ROOT_TINY = 8;
inline constexpr int32_t STEDC_THREADS_PER_ROOT_SMALL = 32;
inline constexpr int32_t STEDC_THREADS_PER_ROOT_MEDIUM = 32;
inline constexpr int32_t STEDC_THREADS_PER_ROOT_LARGE = 32;
inline constexpr int32_t STEDC_THREADS_PER_ROOT_XLARGE = 32;

inline constexpr int32_t STEDC_WG_MULTIPLIER_TINY = 1;
inline constexpr int32_t STEDC_WG_MULTIPLIER_SMALL = 1;
inline constexpr int32_t STEDC_WG_MULTIPLIER_MEDIUM = 1;
inline constexpr int32_t STEDC_WG_MULTIPLIER_LARGE = 1;
inline constexpr int32_t STEDC_WG_MULTIPLIER_XLARGE = 1;

inline constexpr int32_t ormqr_block_size_for_n(int32_t n) {
    if (n <= 64) return ORMQR_BLOCK_SIZE_TINY;
    if (n <= 128) return ORMQR_BLOCK_SIZE_SMALL;
    if (n <= 256) return ORMQR_BLOCK_SIZE_MEDIUM;
    if (n <= 512) return ORMQR_BLOCK_SIZE_LARGE;
    return ORMQR_BLOCK_SIZE_XLARGE;
}

inline constexpr int32_t sytrd_block_size_for_n(int32_t n) {
    if (n <= 64) return SYTRD_BLOCK_SIZE_TINY;
    if (n <= 128) return SYTRD_BLOCK_SIZE_SMALL;
    if (n <= 256) return SYTRD_BLOCK_SIZE_MEDIUM;
    if (n <= 512) return SYTRD_BLOCK_SIZE_LARGE;
    return SYTRD_BLOCK_SIZE_XLARGE;
}

inline constexpr int32_t latrd_lower_panel_wg_hint() { return LATRD_LOWER_PANEL_WG_HINT; }

inline constexpr int32_t stedc_recursion_threshold_for_n(int32_t n) {
    if (n <= 64) return STEDC_RECURSION_THRESHOLD_TINY;
    if (n <= 128) return STEDC_RECURSION_THRESHOLD_SMALL;
    if (n <= 256) return STEDC_RECURSION_THRESHOLD_MEDIUM;
    if (n <= 512) return STEDC_RECURSION_THRESHOLD_LARGE;
    return STEDC_RECURSION_THRESHOLD_XLARGE;
}

inline constexpr int32_t stedc_merge_variant_for_n(int32_t n) {
    if (n <= 64) return STEDC_MERGE_VARIANT_TINY;
    if (n <= 128) return STEDC_MERGE_VARIANT_SMALL;
    if (n <= 256) return STEDC_MERGE_VARIANT_MEDIUM;
    if (n <= 512) return STEDC_MERGE_VARIANT_LARGE;
    return STEDC_MERGE_VARIANT_XLARGE;
}

inline constexpr int32_t stedc_threads_per_root_for_n(int32_t n) {
    if (n <= 64) return STEDC_THREADS_PER_ROOT_TINY;
    if (n <= 128) return STEDC_THREADS_PER_ROOT_SMALL;
    if (n <= 256) return STEDC_THREADS_PER_ROOT_MEDIUM;
    if (n <= 512) return STEDC_THREADS_PER_ROOT_LARGE;
    return STEDC_THREADS_PER_ROOT_XLARGE;
}

inline constexpr int32_t stedc_wg_multiplier_for_n(int32_t n) {
    if (n <= 64) return STEDC_WG_MULTIPLIER_TINY;
    if (n <= 128) return STEDC_WG_MULTIPLIER_SMALL;
    if (n <= 256) return STEDC_WG_MULTIPLIER_MEDIUM;
    if (n <= 512) return STEDC_WG_MULTIPLIER_LARGE;
    return STEDC_WG_MULTIPLIER_XLARGE;
}

} // namespace batchlas::tuning
