#pragma once

// The *constants* in this file are auto-generated by
// evaluation/tuning/generate_tuning_header.py from build/tuning/profile.json.
// Do not edit the constants manually -- regenerate instead.
//
// The accessors at the bottom are hand-maintained (and mirrored in the
// generator's template) so that every tuning knob can be overridden at RUNTIME
// via an environment variable, which lets one process A/B a retune with no
// rebuild. See `tuning_env_override` for the contract.

#include <cstdint>
#include <cstdlib>

namespace batchlas::tuning {

namespace detail {

// Runtime override for a compile-time tuning constant.
//
// Contract (matches BATCHLAS_SY2SB_ORMQR_NB in src/extensions/sytrd_sy2sb.cc and
// BATCHLAS_SYEV_TWO_STAGE_KD in src/extensions/two_stage_common.hh):
//   * read FRESH on every call, never cached, so an A/B harness can flip the
//     variable between runs (or between calls) inside one process;
//   * unset / empty / unparseable / trailing garbage / non-positive  ->
//     the compiled constant, i.e. bit-for-bit today's behaviour.
//
// HAZARD: every accessor below is consulted by *_buffer_size() queries as well
// as by the matching solve. The variable must therefore NOT be changed between
// a buffer-size query and its call -- that desynchronises the allocated
// workspace from the block width actually used. Flip it between runs, not
// inside one.
inline int32_t tuning_env_override(const char* name, int32_t fallback) {
    const char* v = std::getenv(name);
    if (v == nullptr || *v == '\0') return fallback;
    char* end = nullptr;
    const long parsed = std::strtol(v, &end, 10);
    if (end == v || *end != '\0') return fallback;   // not a clean integer
    if (parsed <= 0 || parsed > 2147483647L) return fallback;  // non-positive / out of range
    return static_cast<int32_t>(parsed);
}

} // namespace detail

inline constexpr int32_t ORMQR_BLOCK_SIZE_TINY = 16;
inline constexpr int32_t ORMQR_BLOCK_SIZE_SMALL = 16;
inline constexpr int32_t ORMQR_BLOCK_SIZE_MEDIUM = 16;
inline constexpr int32_t ORMQR_BLOCK_SIZE_LARGE = 16;
inline constexpr int32_t ORMQR_BLOCK_SIZE_XLARGE = 16;

inline constexpr int32_t SYTRD_BLOCK_SIZE_TINY = 8;
inline constexpr int32_t SYTRD_BLOCK_SIZE_SMALL = 8;
inline constexpr int32_t SYTRD_BLOCK_SIZE_MEDIUM = 16;
inline constexpr int32_t SYTRD_BLOCK_SIZE_LARGE = 24;
inline constexpr int32_t SYTRD_BLOCK_SIZE_XLARGE = 32;

inline constexpr int32_t LATRD_LOWER_PANEL_WG_HINT_TINY = 0;
inline constexpr int32_t LATRD_LOWER_PANEL_WG_HINT_SMALL = 0;
inline constexpr int32_t LATRD_LOWER_PANEL_WG_HINT_MEDIUM = 0;
inline constexpr int32_t LATRD_LOWER_PANEL_WG_HINT_LARGE = 0;
inline constexpr int32_t LATRD_LOWER_PANEL_WG_HINT_XLARGE = 0;

inline constexpr int32_t SYTRD_FUSE_PANEL_UPDATE_TINY = 0;
inline constexpr int32_t SYTRD_FUSE_PANEL_UPDATE_SMALL = 0;
inline constexpr int32_t SYTRD_FUSE_PANEL_UPDATE_MEDIUM = 0;
inline constexpr int32_t SYTRD_FUSE_PANEL_UPDATE_LARGE = 0;
inline constexpr int32_t SYTRD_FUSE_PANEL_UPDATE_XLARGE = 0;

inline constexpr int32_t STEDC_RECURSION_THRESHOLD_TINY = 16;
inline constexpr int32_t STEDC_RECURSION_THRESHOLD_SMALL = 32;
inline constexpr int32_t STEDC_RECURSION_THRESHOLD_MEDIUM = 32;
inline constexpr int32_t STEDC_RECURSION_THRESHOLD_LARGE = 32;
inline constexpr int32_t STEDC_RECURSION_THRESHOLD_XLARGE = 32;

// StedcMergeVariant: 1 = Fused (one work-group per merge), 2 = FusedCta
// (sub-group partitions, one per secular root).
//
// These were 2. FusedCta is currently *wrong*: it fails stedc_tests'
// BatchedRandomMatrices and FusedCtaConditionedHeavyDeflation in both
// precisions, the latter returning NaN, and the defect is confined to its
// partition-parallel root solve. It had been masked by a deadlock in the same
// kernel (fixed separately), which is why the tables were tuned to it. It is
// also 2-12% slower than Fused on an RTX 4090 across n = 64..256 x batch =
// 128..2048, on both STEDC drivers. Point back at 2 once the root solve is
// fixed and re-tuned.
inline constexpr int32_t STEDC_MERGE_VARIANT_TINY = 1;
inline constexpr int32_t STEDC_MERGE_VARIANT_SMALL = 1;
inline constexpr int32_t STEDC_MERGE_VARIANT_MEDIUM = 1;
inline constexpr int32_t STEDC_MERGE_VARIANT_LARGE = 1;
inline constexpr int32_t STEDC_MERGE_VARIANT_XLARGE = 1;

inline constexpr int32_t STEDC_THREADS_PER_ROOT_TINY = 4;
inline constexpr int32_t STEDC_THREADS_PER_ROOT_SMALL = 4;
inline constexpr int32_t STEDC_THREADS_PER_ROOT_MEDIUM = 4;
inline constexpr int32_t STEDC_THREADS_PER_ROOT_LARGE = 4;
inline constexpr int32_t STEDC_THREADS_PER_ROOT_XLARGE = 8;

inline constexpr int32_t STEDC_WG_MULTIPLIER_TINY = 8;
inline constexpr int32_t STEDC_WG_MULTIPLIER_SMALL = 8;
inline constexpr int32_t STEDC_WG_MULTIPLIER_MEDIUM = 8;
inline constexpr int32_t STEDC_WG_MULTIPLIER_LARGE = 8;
inline constexpr int32_t STEDC_WG_MULTIPLIER_XLARGE = 8;

// ---------------------------------------------------------------------------
// Compile-time tables (constexpr, usable in constant expressions).
// ---------------------------------------------------------------------------

inline constexpr int32_t ormqr_block_size_default_for_n(int32_t n) {
    if (n <= 64) return ORMQR_BLOCK_SIZE_TINY;
    if (n <= 128) return ORMQR_BLOCK_SIZE_SMALL;
    if (n <= 256) return ORMQR_BLOCK_SIZE_MEDIUM;
    if (n <= 512) return ORMQR_BLOCK_SIZE_LARGE;
    return ORMQR_BLOCK_SIZE_XLARGE;
}

inline constexpr int32_t sytrd_block_size_default_for_n(int32_t n) {
    if (n <= 64) return SYTRD_BLOCK_SIZE_TINY;
    if (n <= 128) return SYTRD_BLOCK_SIZE_SMALL;
    if (n <= 256) return SYTRD_BLOCK_SIZE_MEDIUM;
    if (n <= 512) return SYTRD_BLOCK_SIZE_LARGE;
    return SYTRD_BLOCK_SIZE_XLARGE;
}

inline constexpr int32_t latrd_lower_panel_wg_hint_default_for_n(int32_t n) {
    if (n <= 64) return LATRD_LOWER_PANEL_WG_HINT_TINY;
    if (n <= 128) return LATRD_LOWER_PANEL_WG_HINT_SMALL;
    if (n <= 256) return LATRD_LOWER_PANEL_WG_HINT_MEDIUM;
    if (n <= 512) return LATRD_LOWER_PANEL_WG_HINT_LARGE;
    return LATRD_LOWER_PANEL_WG_HINT_XLARGE;
}

inline constexpr int32_t stedc_recursion_threshold_default_for_n(int32_t n) {
    if (n <= 64) return STEDC_RECURSION_THRESHOLD_TINY;
    if (n <= 128) return STEDC_RECURSION_THRESHOLD_SMALL;
    if (n <= 256) return STEDC_RECURSION_THRESHOLD_MEDIUM;
    if (n <= 512) return STEDC_RECURSION_THRESHOLD_LARGE;
    return STEDC_RECURSION_THRESHOLD_XLARGE;
}

inline constexpr int32_t stedc_merge_variant_default_for_n(int32_t n) {
    if (n <= 64) return STEDC_MERGE_VARIANT_TINY;
    if (n <= 128) return STEDC_MERGE_VARIANT_SMALL;
    if (n <= 256) return STEDC_MERGE_VARIANT_MEDIUM;
    if (n <= 512) return STEDC_MERGE_VARIANT_LARGE;
    return STEDC_MERGE_VARIANT_XLARGE;
}

inline constexpr int32_t stedc_threads_per_root_default_for_n(int32_t n) {
    if (n <= 64) return STEDC_THREADS_PER_ROOT_TINY;
    if (n <= 128) return STEDC_THREADS_PER_ROOT_SMALL;
    if (n <= 256) return STEDC_THREADS_PER_ROOT_MEDIUM;
    if (n <= 512) return STEDC_THREADS_PER_ROOT_LARGE;
    return STEDC_THREADS_PER_ROOT_XLARGE;
}

inline constexpr int32_t stedc_wg_multiplier_default_for_n(int32_t n) {
    if (n <= 64) return STEDC_WG_MULTIPLIER_TINY;
    if (n <= 128) return STEDC_WG_MULTIPLIER_SMALL;
    if (n <= 256) return STEDC_WG_MULTIPLIER_MEDIUM;
    if (n <= 512) return STEDC_WG_MULTIPLIER_LARGE;
    return STEDC_WG_MULTIPLIER_XLARGE;
}

// ---------------------------------------------------------------------------
// Runtime accessors. These are what production code calls; each one consults
// its environment variable first and falls back to the table above.
// ---------------------------------------------------------------------------

inline int32_t ormqr_block_size_for_n(int32_t n) {
    return detail::tuning_env_override("BATCHLAS_TUNE_ORMQR_BLOCK_SIZE",
                                       ormqr_block_size_default_for_n(n));
}

inline int32_t sytrd_block_size_for_n(int32_t n) {
    return detail::tuning_env_override("BATCHLAS_TUNE_SYTRD_BLOCK_SIZE",
                                       sytrd_block_size_default_for_n(n));
}

inline int32_t latrd_lower_panel_wg_hint_for_n(int32_t n) {
    return detail::tuning_env_override("BATCHLAS_TUNE_LATRD_WG_HINT",
                                       latrd_lower_panel_wg_hint_default_for_n(n));
}

inline int32_t latrd_lower_panel_wg_hint() { return latrd_lower_panel_wg_hint_for_n(256); }

inline constexpr bool sytrd_fuse_panel_update_for_n(int32_t n) {
    if (n <= 64) return SYTRD_FUSE_PANEL_UPDATE_TINY != 0;
    if (n <= 128) return SYTRD_FUSE_PANEL_UPDATE_SMALL != 0;
    if (n <= 256) return SYTRD_FUSE_PANEL_UPDATE_MEDIUM != 0;
    if (n <= 512) return SYTRD_FUSE_PANEL_UPDATE_LARGE != 0;
    return SYTRD_FUSE_PANEL_UPDATE_XLARGE != 0;
}

inline int32_t stedc_recursion_threshold_for_n(int32_t n) {
    return detail::tuning_env_override("BATCHLAS_TUNE_STEDC_RECURSION_THRESHOLD",
                                       stedc_recursion_threshold_default_for_n(n));
}

// NOTE: the returned value is cast to StedcMergeVariant by the callers. 0 is
// StedcMergeVariant::Auto, which would re-enter tuning resolution, so 0 (like
// every non-positive value) falls back to the compiled constant.
inline int32_t stedc_merge_variant_for_n(int32_t n) {
    return detail::tuning_env_override("BATCHLAS_TUNE_STEDC_MERGE_VARIANT",
                                       stedc_merge_variant_default_for_n(n));
}

inline int32_t stedc_threads_per_root_for_n(int32_t n) {
    return detail::tuning_env_override("BATCHLAS_TUNE_STEDC_THREADS_PER_ROOT",
                                       stedc_threads_per_root_default_for_n(n));
}

inline int32_t stedc_wg_multiplier_for_n(int32_t n) {
    return detail::tuning_env_override("BATCHLAS_TUNE_STEDC_WG_MULTIPLIER",
                                       stedc_wg_multiplier_default_for_n(n));
}

} // namespace batchlas::tuning
