#pragma once

// This file is auto-generated by CMake - do not edit manually
// It contains compile-time configuration for available backends

// HOST backend (netlib BLAS/LAPACK)
#define BATCHLAS_HAS_HOST_BACKEND 0

// GPU backends determined at configure time
#define BATCHLAS_HAS_CUDA_BACKEND 0
#define BATCHLAS_HAS_ROCM_BACKEND 0
#define BATCHLAS_HAS_MKL_BACKEND 0

// Whether CPU SYCL kernel targets are compiled
#define BATCHLAS_HAS_CPU_TARGET 0

// Helper macros for conditional compilation
#if BATCHLAS_HAS_CUDA_BACKEND
  #define BATCHLAS_IF_CUDA(x) x
#else
  #define BATCHLAS_IF_CUDA(x)
#endif

#if BATCHLAS_HAS_ROCM_BACKEND
  #define BATCHLAS_IF_ROCM(x) x
#else
  #define BATCHLAS_IF_ROCM(x)
#endif

#if BATCHLAS_HAS_MKL_BACKEND
  #define BATCHLAS_IF_MKL(x) x
#else
  #define BATCHLAS_IF_MKL(x)
#endif

// For convenience - define if any GPU backend is available
#if BATCHLAS_HAS_CUDA_BACKEND || BATCHLAS_HAS_ROCM_BACKEND || BATCHLAS_HAS_MKL_BACKEND
  #define BATCHLAS_HAS_GPU_BACKEND 1
#else
  #define BATCHLAS_HAS_GPU_BACKEND 0
#endif
