# Compilation caching (ccache), on by default when ccache is found.
#
# ccache reproduces -fsycl fat objects (nvptx64 and native_cpu images included)
# byte for byte. The settings it needs are not its defaults, so they reach it as
# environment variables through a generated wrapper (a developer's ccache.conf is
# not ours to edit):
#   CCACHE_DEPEND      hash the -MD depfile; preprocessor mode re-preprocesses
#                      every -fsycl phase and makes a miss ~50% slower.
#   CCACHE_BASEDIR +   hash paths relative to the base, so a second checkout or
#   CCACHE_NOHASHDIR   worktree hits the entries of the first.
#   CCACHE_SLOPPINESS  a fresh checkout's headers are all "just modified".
# Compiles only: device links and test links are not cached.
# Traps: a header added that SHADOWS one later on the -I path can return a stale
# object (`ccache -C`); NOHASHDIR keeps the first tree's DW_AT_comp_dir, so set
# BATCHLAS_CCACHE_SHARE_ACROSS_TREES=OFF for source-level debugging.
# evidence: docs/developer/agent-guide.md section 7 (Build Performance)

option(BATCHLAS_USE_CCACHE "Cache C++ compilations with ccache when it is available" ON)
option(BATCHLAS_CCACHE_SHARE_ACROSS_TREES
    "Let separate checkouts/worktrees share cache entries (see DW_AT_comp_dir caveat)" ON)
set(BATCHLAS_CCACHE_MAXSIZE "20G" CACHE STRING "ccache size limit")

# Deepest common parent of the source and binary trees. "/" would make every path
# relative to a cwd that differs between trees, so that falls back to $HOME.
function(_batchlas_ccache_common_parent out_var)
    file(TO_CMAKE_PATH "${CMAKE_SOURCE_DIR}" _a)
    file(TO_CMAKE_PATH "${CMAKE_BINARY_DIR}" _b)
    string(REPLACE "/" ";" _a_parts "${_a}")
    string(REPLACE "/" ";" _b_parts "${_b}")
    set(_common "")
    set(_i 0)
    list(LENGTH _a_parts _a_len)
    list(LENGTH _b_parts _b_len)
    while(_i LESS _a_len AND _i LESS _b_len)
        list(GET _a_parts ${_i} _pa)
        list(GET _b_parts ${_i} _pb)
        if(NOT _pa STREQUAL _pb)
            break()
        endif()
        if(NOT _pa STREQUAL "")
            string(APPEND _common "/${_pa}")
        endif()
        math(EXPR _i "${_i} + 1")
    endwhile()
    if(_common STREQUAL "")
        set(_common "$ENV{HOME}")
    endif()
    set(${out_var} "${_common}" PARENT_SCOPE)
endfunction()

_batchlas_ccache_common_parent(_batchlas_ccache_default_base)
set(BATCHLAS_CCACHE_BASEDIR "${_batchlas_ccache_default_base}" CACHE PATH
    "Paths below this are hashed relative, so sibling checkouts share cache entries")

set(_batchlas_ccache_launcher "${CMAKE_BINARY_DIR}/batchlas-ccache")
set(_batchlas_owns_launcher OFF)
if(CMAKE_CXX_COMPILER_LAUNCHER STREQUAL _batchlas_ccache_launcher)
    set(_batchlas_owns_launcher ON)
endif()

if(NOT BATCHLAS_USE_CCACHE)
    if(_batchlas_owns_launcher)
        unset(CMAKE_CXX_COMPILER_LAUNCHER CACHE)
        unset(CMAKE_CXX_COMPILER_LAUNCHER)
    endif()
    return()
endif()

# Under add_subdirectory()/FetchContent a cached launcher would reroute the
# CONSUMING project's compiler. BATCHLAS_IS_TOP_LEVEL does not exist yet here.
if(NOT CMAKE_SOURCE_DIR STREQUAL PROJECT_SOURCE_DIR)
    message(STATUS "BatchLAS is a subproject: leaving CMAKE_CXX_COMPILER_LAUNCHER to the parent project")
    return()
endif()

if(CMAKE_CXX_COMPILER_LAUNCHER AND NOT _batchlas_owns_launcher)
    message(STATUS "CMAKE_CXX_COMPILER_LAUNCHER already set - leaving it alone: ${CMAKE_CXX_COMPILER_LAUNCHER}")
    return()
endif()

find_program(BATCHLAS_CCACHE_PROGRAM ccache HINTS "$ENV{HOME}/.local/bin")
if(NOT BATCHLAS_CCACHE_PROGRAM)
    if(_batchlas_owns_launcher)
        unset(CMAKE_CXX_COMPILER_LAUNCHER CACHE)
        unset(CMAKE_CXX_COMPILER_LAUNCHER)
    endif()
    message(STATUS "ccache not found - compilations will not be cached "
                   "(install: static binary from https://github.com/ccache/ccache/releases into ~/.local/bin)")
    return()
endif()

set(_batchlas_ccache_env
    "export CCACHE_DEPEND=1\nexport CCACHE_MAXSIZE=${BATCHLAS_CCACHE_MAXSIZE}\n"
    "export CCACHE_SLOPPINESS=include_file_mtime,include_file_ctime,time_macros,pch_defines,locale\n")
if(BATCHLAS_CCACHE_SHARE_ACROSS_TREES)
    list(APPEND _batchlas_ccache_env
        "export CCACHE_BASEDIR=${BATCHLAS_CCACHE_BASEDIR}\nexport CCACHE_NOHASHDIR=1\n")
endif()
string(REPLACE ";" "" _batchlas_ccache_env "${_batchlas_ccache_env}")

# file(COPY ... FILE_PERMISSIONS), not file(CHMOD): the latter needs CMake 3.19.
file(WRITE "${CMAKE_BINARY_DIR}/CMakeFiles/batchlas-ccache-stage/batchlas-ccache"
    "#!/bin/sh\n"
    "# Generated by cmake/BatchLASCcache.cmake - do not edit.\n"
    "${_batchlas_ccache_env}"
    "exec \"${BATCHLAS_CCACHE_PROGRAM}\" \"$@\"\n"
)
file(COPY "${CMAKE_BINARY_DIR}/CMakeFiles/batchlas-ccache-stage/batchlas-ccache"
    DESTINATION "${CMAKE_BINARY_DIR}"
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)

set(CMAKE_CXX_COMPILER_LAUNCHER "${_batchlas_ccache_launcher}" CACHE STRING "" FORCE)

if(BATCHLAS_CCACHE_SHARE_ACROSS_TREES)
    message(STATUS "ccache enabled (depend mode, shared below ${BATCHLAS_CCACHE_BASEDIR}): ${BATCHLAS_CCACHE_PROGRAM}")
else()
    message(STATUS "ccache enabled (depend mode, this tree only): ${BATCHLAS_CCACHE_PROGRAM}")
endif()
