# Configure-time staleness check of tuned/*.txt (docs/design/flat-kernel-selection.md §6.5).
# Each table header carries kernels=<hash>; the hash is recomputed from the kernel-source list in
# tools/tune/<op>_spec.cc (between the kernel-sources-begin/-end markers): sha256 over the lines
# "<sha256(file)>  <path>\n" in list order, first 8 hex digits. .github/ci/check_tuned_tables.py
# and batchlas_tune compute the same value. A mismatch, or kernels=unknown, is a warning only:
# the table stays in use.

function(_batchlas_tune_kernel_hash spec out_var)
    file(STRINGS "${spec}" _lines REGEX "kernel-sources-|\"")
    set(_inside FALSE)
    set(_manifest "")
    foreach(_line IN LISTS _lines)
        if(_line MATCHES "kernel-sources-begin")
            set(_inside TRUE)
        elseif(_line MATCHES "kernel-sources-end")
            break()
        elseif(_inside)
            string(REGEX MATCHALL "\"[^\"]+\"" _paths "${_line}")
            foreach(_q IN LISTS _paths)
                string(REPLACE "\"" "" _p "${_q}")
                if(NOT EXISTS "${PROJECT_SOURCE_DIR}/${_p}")
                    set(${out_var} "missing:${_p}" PARENT_SCOPE)
                    return()
                endif()
                file(SHA256 "${PROJECT_SOURCE_DIR}/${_p}" _h)
                string(APPEND _manifest "${_h}  ${_p}\n")
            endforeach()
        endif()
    endforeach()
    string(SHA256 _all "${_manifest}")
    string(SUBSTRING "${_all}" 0 8 _short)
    set(${out_var} "${_short}" PARENT_SCOPE)
endfunction()

function(batchlas_check_tuned_tables tuned_dir)
    file(GLOB _tables "${tuned_dir}/*.txt")
    list(SORT _tables)
    set(_report "")
    foreach(_t IN LISTS _tables)
        get_filename_component(_name "${_t}" NAME)
        string(REGEX MATCH "^[^.]+" _op "${_name}")
        set(_spec "${PROJECT_SOURCE_DIR}/tools/tune/${_op}_spec.cc")
        if(NOT EXISTS "${_spec}")
            continue()
        endif()
        if(NOT DEFINED _hash_${_op})
            _batchlas_tune_kernel_hash("${_spec}" _hash_${_op})
        endif()
        file(STRINGS "${_t}" _head REGEX "^#.*kernels=")
        set(_have "unknown")
        if(_head MATCHES "kernels=([^ ;]+)")
            set(_have "${CMAKE_MATCH_1}")
        endif()
        if(NOT _have STREQUAL _hash_${_op})
            string(APPEND _report "  tuned/${_name} is stale (kernels ${_have} -> ${_hash_${_op}}); run tools/tune\n")
        endif()
    endforeach()
    if(_report)
        message(WARNING "stale tuned selection tables (§6.5; they stay in use):\n${_report}")
    endif()
endfunction()
