# Script mode: cmake -DTUNED_DIR=<dir> -DOUT=<file.cc> -DSELECT_HH=<select.hh> -P this-file
# Embeds every <dir>/*.txt as {file name, contents} for select::embedded_tables()
# (docs/design/flat-kernel-selection.md §5.4). Zero files is valid: the array keeps a sentinel.
file(GLOB _files "${TUNED_DIR}/*.txt")
list(SORT _files)
set(_arrays "")
set(_body "")
set(_n 0)
foreach(_f IN LISTS _files)
    get_filename_component(_name "${_f}" NAME)
    # select.cc skips any other name, so a misnamed table would silently never be used.
    if(NOT _name MATCHES "^[^.]+\\.[^.]+\\.[^.]+\\.txt$")
        message(FATAL_ERROR "${_f}: a tuned table must be named <op>.<dtype>.<device>.txt")
    endif()
    file(READ "${_f}" _text)
    string(FIND "${_text}" ")batchlas_tbl" _clash)
    if(NOT _clash EQUAL -1)
        message(FATAL_ERROR "${_f} contains the raw-string delimiter )batchlas_tbl")
    endif()
    # One char array per table, its length from sizeof: a string_view built from a bare literal
    # runs a constexpr strlen, and ~0.5 MB of tables exceeds clang's constexpr step limit.
    string(APPEND _arrays "constexpr char kText${_n}[] = R\"batchlas_tbl(${_text})batchlas_tbl\";\n")
    string(APPEND _body "    {\"${_name}\", {kText${_n}, sizeof(kText${_n}) - 1}},\n")
    math(EXPR _n "${_n} + 1")
endforeach()

set(_src "// Generated by cmake/BatchLASEmbedTables.cmake from tuned/*.txt. Do not edit.\n")
string(APPEND _src "#include \"${SELECT_HH}\"\n\nnamespace batchlas::select {\nnamespace {\n")
string(APPEND _src "${_arrays}constexpr EmbeddedTable kTables[] = {\n${_body}    {\"\", \"\"},\n};\n}  // namespace\n\n")
string(APPEND _src "std::span<const EmbeddedTable> embedded_tables() { return {kTables, ${_n}}; }\n\n")
string(APPEND _src "}  // namespace batchlas::select\n")

set(_old "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" _old)
endif()
# Unchanged text keeps its timestamp so the TU is not recompiled.
if(NOT _old STREQUAL _src)
    file(WRITE "${OUT}" "${_src}")
endif()
